export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const ADD_TO_CART = 'ADD_TO_CART'

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_ERROR = 'FETCH_ITEM_ERROR';

export const FETCH_CART_ITEM_REQUEST = 'FETCH_CART_ITEM_REQUEST';
export const FETCH_CART_ITEM_SUCCESS = 'FETCH_CART_ITEM_SUCCESS';
export const FETCH_CART_ITEM_ERROR = 'FETCH_CART_ITEM_ERROR';

export const ADD_ITEM_DB = 'ADD_ITEM_DB';
export const REMOVE_ITEM_DB = 'REMOVE_ITEM_DB';
